### PR TITLE
chore: remove packages as a cmd module

### PR DESCRIPTION
**Pull request by varl**
This removes d2-packages as a cmd module from the main cli.

Some apps still rely on it, but they can use `d2-packages` directly.

### CODE REVIEW

**Comment by amcgee** [comment]
Looks good, but seems there are a ton of unrelated yarn.lock changes and for some reason there's still a `cli-packages` in there?

**Comment by varl** [comment]
Yeah, I don't know what yarn is up to, but I reacted to the `cli-packages` still being there to `cli-style`: https://github.com/dhis2/cli-style/blob/master/package.json#L22

**Comment by varl** [comment]
I'll take another look at what Yarn is doing tomorrow.

**Comment by amcgee** [comment]
> Yeah, I don't know what yarn is up to, but I reacted to the `cli-packages` still being there to `cli-style`: https://github.com/dhis2/cli-style/blob/master/package.json#L22

Ah yeah, forgot we put `release` there.

**Pull request merged**
