### PR TITLE
ci: ping netlify to rebuild on change

### PR DESCRIPTION
**Pull request by ismay**
Todo:

- [x] Only rebuild when files related to the docs change
- [x] Add `NETLIFY_DEVELOPER_DOCS_TOKEN` to repo secrets
- [ ] Add to remaining repos: cli-style, app-platform, app-runtime, cli-utils-cypress

Links:

- https://app.netlify.com/sites/dhis2-developer-portal/overview
- https://github.com/dhis2/developer-portal/
- https://docs.netlify.com/configure-builds/build-hooks/
- https://github.com/dhis2/developer-portal/blob/main/docs-migrate.js
- https://github.com/orgs/community/discussions/27027
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore

### CODE REVIEW

**Comment by Topener** [comment]
For this repository, and some of the other ones too, the root `CHANGELOG.md` is also relevant

**Comment by ismay** [comment]
> For this repository, and some of the other ones too, the root CHANGELOG.md is also relevant

Ah that's good to know, thanks. I'll add it.

**Comment by ismay** [comment]
@Topener Let me know what you think. If you approve this PR we can merge it and try it out.

**Review by Topener — APPROVED** [review]
LGTM!

**Pull request merged**
