### PR TITLE
chore: pin all @dhis2 scoped package versions

### PR DESCRIPTION
**Pull request by varl**
Change to pinned versions for `@dhis2`-scoped packages to allow Greenkeeper to keep them updated for us.

Also update `@dhis2/cli-style` to get the new lint rules pulled in.

### CODE REVIEW

**Comment by amcgee** [comment]
@Mohammer5 agreed, that probably makes this a minor bump instead of a "chore"?

**Comment by Mohammer5** [comment]
> @Mohammer5 agreed, that probably makes this a minor bump instead of a "chore"?

@amcgee I don't know, not necessarily. Commit message can stay `chore` and if nothing changes functionality-wise, I wouldn't say it's worth to increment the minor version number either. 
On the other side, better safe than sorry?

**Comment by varl** [comment]
> @varl it looks like you're not working off the latest master branch, the current version of CLI packages in this repo are all `v1.0.2`

Whoops!

**Comment by varl** [comment]
I think the pin change is a `chore` (doesn't need a release).

Changing the version of `cli-style` warrants a release thought because it's actually a `feat` because of the change in `cli-style` which adds functionality for ESLint, etc.

**Comment by varl** [comment]
Closing this, and re-opening a new PR.

**Pull request closed without merging**
