### PR TITLE
docs: add cypress to sidebar

### PR DESCRIPTION
**Pull request by deboragaleano**
This PR closes https://jira.dhis2.org/browse/CLI-27

### CODE REVIEW

**Review by varl — COMMENTED** [review]
Why is there a new `yarn.lock` file?

**Comment by deboragaleano** [comment]
> Why is there a new `yarn.lock` file?

@varl I'm not really sure what happened there, maybe I should delete it? 🤔

**Comment by varl** [comment]
> @varl I'm not really sure what happened there, maybe I should delete it?

Yeah, please do. :)

**Comment by deboragaleano** [comment]
@varl Done 👍

**Comment by amcgee** [comment]
@deboragaleano probably you need to revert it, not delete it?

**Comment by varl** [comment]
Yeah, I should have specified that I meant "delete it from the PR". We still need the file as it was before. :blush:

**Review by varl — APPROVED** [review]

**Comment by deboragaleano** [comment]
> Yeah, I should have specified that I meant "delete it from the PR". We still need the file as it was before. 😊

sorry about this and thanks for reverting !  @varl

**Comment by varl** [comment]
Don't worry about it. I figured you are busy with the Academy and this was quicker for me to just fix and push instead of going back and forth. :)

**Pull request merged**
