### PR TITLE
chore: pin @dhis2-scoped package versions

### PR DESCRIPTION
**Pull request by varl**
Replaces: #37

### CODE REVIEW

**Comment by varl** [comment]
This only pins versions, and we can let Greenkeeper update to see that everything works as intended.

**Comment by amcgee** [comment]
@varl nice.  Probably good to also update the reference to `@dhis2/cli-style` in the root `package.json` (used by the pre-commit hook) so that we don't have both version ranges in the yarn.lock file.  There's still a carat-version cli-helpers-engine which I believe comes from `cli-style`, so  hopefully that will drop out when greenkeeper updates `cli-style`

**Comment by varl** [comment]
Search and replace fail on this branch. Fixeed in c88b526.

**Comment by amcgee** [comment]
The `yarn.lock` update seems excessive (dozens of added deps) and still include the `cli-style@^3.0.2` entry...?

**Comment by varl** [comment]
From what I can trace, most of the added deps are from `semantic-release@^15.13.3`, which is also added by this PR. Which I do not understand. We should have that already.

**Comment by varl** [comment]
Running `yarn install` on master updates the `yarn.lock` as well:

[yarn.lock.txt](https://github.com/dhis2/cli/files/3153303/yarn.lock.txt)

**Comment by amcgee** [comment]
This looks OK, but we'll actually need to change the release script as well since it automatically updates dependency versions using ^ ranges in a monorepo

**Comment by varl** [comment]
Done in d00acd7.

**Pull request merged**
